name: Create Pull Request
on:
  push:
    branches:
      - integration

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create Pull Request
      run: gh pr create
      env:
        GITHUB_TOKEN: ${{ github.token }}
